Reduced jumper image resolution
ERROR: Jumper renders filesize too large and negatively impacted page
load time. Reduced resolution and therefore size from ~6MB @ 7000*5000px
to <500kb @ 1500px*1071px