Updated products.html
ERROR: Extra space in the QC header hyperlink
NOW: Hopeful of removal of space in QC header hyperlink resulting in no displacement between webpages.